global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "danirogmans@gmail.com"
  smtp_auth_username: "danirogmans@gmail.com"
  smtp_auth_password: "REDACTED"
  smtp_require_tls: false

route:
  receiver: "email"

receivers:
  - name: "email"
    email_configs:
      - to: "danirogmans@gmail.com"
        send_resolved: true
