{
 "title": "first_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Inference time per call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "inference_time_histogram_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Yes feedback",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "feedback_yes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of No feedback",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "feedback_no_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 24 },
   "targets": [
    { "expr": "inference_time_histogram_sum", "legendFormat": "__auto" },
    { "expr": "feedback_no_total", "legendFormat": "__auto" },
    { "expr": "feedback_yes_total", "legendFormat": "__auto" },
    { "expr": "in_progress_requests", "legendFormat": "__auto" }
   ]
  }
 ]
}