name: Release to GitHub Container Registry

on:
  pull_request:
    branches:
      - main
    types:
      - opened
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v'

env:
  REPO: ghcr.io/remla2024-team14/app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract version
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t app .

      - name: Tag Docker image with version
        run: |
          REPO=ghcr.io/remla2024-team14/app
          VERSION=${{ steps.version.outputs.version }}
          docker tag app $REPO:$VERSION
          docker tag app $REPO:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          REPO=ghcr.io/remla2024-team14/app
          VERSION=${{ steps.version.outputs.version }}
          docker push $REPO:$VERSION
          docker push $REPO:latest

      - name: Trigger release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Release app version ${{ steps.version.outputs.version }}

