name: Release to GitHub Container Registry

on:
  pull_request:
    branches:
      - main
    types:
      - opened
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'       # Semantic versioning (e.g., v1.0.0, v2.3.4)

# env:
#   REPO: ghcr.io/remla2024-team14/app

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version
        id: version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t app .
      
      - name: Parse semantic version from tag
        id: semantic-version
        run: |
          VERSION=${GITHUB_REF:11}
          MAJOR=`echo "$VERSION" | cut -d . -f 1`
          MINOR=`echo "$VERSION" | cut -d . -f 2`
          PATCH=`echo "$VERSION" | cut -d . -f 3`
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=version_major::$MAJOR"
          echo "::set-output name=version_minor::$MINOR"
          echo "::set-output name=version_patch::$PATCH"

        # TODO: semantic-release uses commit messages to determine the type of version bump. Use conventional commit messages for this purpose:
        # fix: prefix for patch changes
        # feat: prefix for minor changes
        # BREAKING CHANGE: in the commit body or footer for major changes
        # See https://github.com/semantic-release/semantic-release for details


      - name: Tag Docker image with distinct versions
        run: |
          IMG=ghcr.io/${{ github.repository }}
          docker tag app $IMG:${{ steps.semantic-version.outputs.version }}
          docker tag app $IMG:latest
          docker tag app $IMG:${{ steps.semantic-version.outputs.version_major }}.${{ steps.semantic-version.outputs.version_minor }}.latest
          docker tag app $IMG:${{ steps.semantic-version.outputs.version_major }}.latest

      - name: Push Docker image to GitHub Container Registry
        run: |
          IMG=ghcr.io/${{ github.repository }}
          docker push $IMG:${{ steps.semantic-version.outputs.version }}
          docker push $IMG:latest
          docker push $IMG:${{ steps.semantic-version.outputs.version_major }}.${{ steps.semantic-version.outputs.version_minor }}.latest
          docker push $IMG:${{ steps.semantic-version.outputs.version_major }}.latest

      - name: Trigger release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Release app version ${{ steps.version.outputs.version }}

